[package]
name = "look_and_say"
version = "0.1.0"
authors = ["Craig Bilner <craig.bilner@news.co.uk>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
